# Generated by Django 4.1 on 2022-09-04 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tod',
            new_name='Todo',
        ),
    ]
